# -*- coding: utf-8 -*-
"""Diabeties.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VLw9XRAK59GgGe2G2Jn8_9_Crk9OWvgt
"""

import pandas as pd

df=pd.read_csv("/content/diabetes_dataset.csv")

df.head()

df.info()

df.columns

df.info()

df["Gender"].unique()

df["Gender"]=df["Gender"].replace({"Female":0,"Male":1})

df.info()

df.select_dtypes(include=["object"]).columns

for i in df.select_dtypes(include=["object"]).columns:
  print (i)

for i in df.select_dtypes(include=["object"]).columns:
  print (i,df[i].unique())

from sklearn.preprocessing import OrdinalEncoder
O = OrdinalEncoder()

for i in df.select_dtypes(include=["object"]).columns:
  df[i]=O.fit_transform(df[[i]])

df.info()

df.select_dtypes(include = ["object"]).columns

df.corr()